# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f92c7efd72d2aed9048f0120f2cb955a1f0c27df1ab8cd1e967ddbcf54e91e43745cc592e805418f47c99d689f34eb564aadf4d2d3dd8dd4fccb51e6bb864b4

test:
  secret_key_base: 8a39d75eeeec8cf6c331f0b2dba75eccfb6ce96198647a33bcf68e81243c4c842eadbd283b4b0f6405b8fcaa7f0dab5b5eb8512d450049a4884d215e9ac326ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
